add Makefile for MSVC
Makefile
dl_make_vs.bat
dl_make_vs_x64.bat
	using zlib,libpng,sdl2 (auto download)
	support x64

make_vs.bat
	using FLIF_USE_STB_IMAGE (extern/stb_image)

flif-enc.cpp
	fix Compiler Error C2765
	'function' : an explicit specialization of a function template cannot have any default arguments

getopt.c .h
	change to LGPL (#32)
	http://www.ludvikjerabek.com/software/

viewer.c
	fix void* arithmetic

flif.h
flif-interface.cpp
	add flag for DLL build and using
	FLIF_BUILD_DLL
	FLIF_USE_DLL